
-- Create menu_items table
CREATE TABLE public.menu_items (
  id TEXT NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  price NUMERIC NOT NULL DEFAULT 0,
  price2 NUMERIC,
  price_label TEXT,
  price_label2 TEXT,
  category TEXT NOT NULL DEFAULT '',
  is_veg BOOLEAN NOT NULL DEFAULT true,
  available BOOLEAN NOT NULL DEFAULT true,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;

-- RLS policies (public access since admin uses password auth, not Supabase auth)
CREATE POLICY "Anyone can view menu items" ON public.menu_items FOR SELECT USING (true);
CREATE POLICY "Anyone can insert menu items" ON public.menu_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Anyone can update menu items" ON public.menu_items FOR UPDATE USING (true);
CREATE POLICY "Anyone can delete menu items" ON public.menu_items FOR DELETE USING (true);

-- Seed default menu items
INSERT INTO public.menu_items (id, name, description, price, price2, price_label, price_label2, category, is_veg, sort_order) VALUES
('w1', 'Classic Chocolate', 'Rich chocolate waffle with classic toppings', 90, NULL, NULL, NULL, 'Waffles', true, 1),
('w2', 'Milkyway', 'Smooth milky chocolate waffle', 90, NULL, NULL, NULL, 'Waffles', true, 2),
('w3', 'Dark Temptation', 'Intense dark chocolate waffle', 90, NULL, NULL, NULL, 'Waffles', true, 3),
('w4', 'Red Velvet', 'Signature red velvet flavored waffle', 90, NULL, NULL, NULL, 'Waffles', true, 4),
('w5', 'Belgian Chocolate', 'Premium Belgian chocolate drizzle', 90, NULL, NULL, NULL, 'Waffles', true, 5),
('w6', 'Eat Me Now', 'Irresistible loaded chocolate waffle', 90, NULL, NULL, NULL, 'Waffles', true, 6),
('w7', 'Americano', 'Coffee-infused chocolate waffle', 90, NULL, NULL, NULL, 'Waffles', true, 7),
('w8', 'Red Velvet Cream Cheese', 'Red velvet with cream cheese topping', 90, NULL, NULL, NULL, 'Waffles', true, 8),
('w9', 'Butterscotch Crunch', 'Crunchy butterscotch waffle', 90, NULL, NULL, NULL, 'Waffles', true, 9),
('w10', 'Maple Butter', 'Classic maple butter glazed waffle', 90, NULL, NULL, NULL, 'Waffles', true, 10),
('w11', 'Bubblegum', 'Fun bubblegum flavored waffle', 90, NULL, NULL, NULL, 'Waffles', true, 11),
('w12', 'Pulpy Orange', 'Refreshing orange flavored waffle', 90, NULL, NULL, NULL, 'Waffles', true, 12),
('w13', 'Chocolate Almond', 'Chocolate waffle with crunchy almonds', 90, NULL, NULL, NULL, 'Waffles', true, 13),
('w14', 'Caramel Kiss', 'Sweet caramel drizzled waffle', 90, NULL, NULL, NULL, 'Waffles', true, 14),
('w15', 'Na Tere Na Mera', 'A unique blend of flavors', 90, NULL, NULL, NULL, 'Waffles', true, 15),
('w16', 'Nutella', 'Loaded with creamy Nutella', 90, NULL, NULL, NULL, 'Waffles', true, 16),
('w17', 'Oreo Cookie', 'Crushed Oreo cookie waffle', 90, NULL, NULL, NULL, 'Waffles', true, 17),
('w18', 'Cocoa Mocha', 'Coffee meets chocolate waffle', 90, NULL, NULL, NULL, 'Waffles', true, 18),
('w19', 'Melody', 'Sweet melody of chocolate', 90, NULL, NULL, NULL, 'Waffles', true, 19),
('w20', 'Bourbon Whisky', 'Bourbon biscuit flavored waffle', 90, NULL, NULL, NULL, 'Waffles', true, 20),
('w21', 'Kitty Katkat', 'Crispy KitKat waffle delight', 90, NULL, NULL, NULL, 'Waffles', true, 21),
('w22', 'Gems Surprise', 'Colorful gems topped waffle', 90, NULL, NULL, NULL, 'Waffles', true, 22),
('w23', 'Coffee Toffee', 'Coffee and toffee fusion', 90, NULL, NULL, NULL, 'Waffles', true, 23),
('w24', 'Rock It Chocolate', 'Intense rocky chocolate waffle', 90, NULL, NULL, NULL, 'Waffles', true, 24),
('w25', 'Munch Mania', 'Crunchy munch bar waffle', 90, NULL, NULL, NULL, 'Waffles', true, 25),
('w26', 'Laila Majnu', 'A pair of flavors in one', 110, NULL, NULL, NULL, 'Waffles', true, 26),
('w27', 'Dark Bourbon', 'Dark/White/Milk chocolate bourbon', 90, NULL, NULL, NULL, 'Waffles', true, 27),
('w38', 'Black Choco', 'Intense black chocolate waffle', 110, NULL, NULL, NULL, 'Waffles', true, 28),
('w39', 'Whiskey Chocolate', 'Whiskey infused chocolate waffle', 90, NULL, NULL, NULL, 'Waffles', true, 29),
('w40', 'Mama Malai', 'Creamy malai flavored waffle', 90, NULL, NULL, NULL, 'Waffles', true, 30),
('w28', 'Pati Patni Aur Woh', 'Triple flavor surprise waffle', 90, NULL, NULL, NULL, 'Waffles', true, 31),
('w29', 'Eclairs', 'Eclairs chocolate waffle', 90, NULL, NULL, NULL, 'Waffles', true, 32),
('w30', 'Jimmy Jimmy', 'Sprinkled jimmies waffle', 90, NULL, NULL, NULL, 'Waffles', true, 33),
('w31', 'Blueberry Cream Crush', 'Fresh blueberry cream waffle', 90, NULL, NULL, NULL, 'Waffles', true, 34),
('w32', 'Strawberry Cream Crush', 'Strawberry cream topped waffle', 90, NULL, NULL, NULL, 'Waffles', true, 35),
('w33', 'Mango Cream Crush', 'Tropical mango cream waffle', 90, NULL, NULL, NULL, 'Waffles', true, 36),
('w34', 'Halwai Se', 'Indian sweet inspired waffle', 90, NULL, NULL, NULL, 'Waffles', true, 37),
('w35', 'Rasmalai Pistachio', 'Rasmalai with pistachio crush', 90, NULL, NULL, NULL, 'Waffles', true, 38),
('w36', 'Banarsi Paan', 'Paan flavored waffle', 90, NULL, NULL, NULL, 'Waffles', true, 39),
('w37', 'Mathura Peda', 'Classic peda inspired waffle', 90, NULL, NULL, NULL, 'Waffles', true, 40),
('w41', 'Brownie Sundae', 'Warm brownie with ice cream', 180, NULL, NULL, NULL, 'Waffles', true, 41),
('w42', 'Ice Cream Sundae', 'Classic ice cream sundae', 150, NULL, NULL, NULL, 'Waffles', true, 42),
('w43', 'Kunafa Kaju', 'Crispy kunafa with cashew filling', 140, NULL, NULL, NULL, 'Waffles', true, 43),
('w44', 'Kunafa Pista', 'Crispy kunafa with pistachio filling', 140, NULL, NULL, NULL, 'Waffles', true, 44),
('w45', 'Kunafa Almond', 'Crispy kunafa with almond filling', 140, NULL, NULL, NULL, 'Waffles', true, 45),
('w46', 'Tiramisu', 'Classic Italian tiramisu dessert', 140, NULL, NULL, NULL, 'Waffles', true, 46),
('w47', 'Biscoff', 'Creamy Biscoff dessert', 140, NULL, NULL, NULL, 'Waffles', true, 47),
('w48', 'White Chocolate', 'Smooth white chocolate waffle', 90, NULL, NULL, NULL, 'Waffles', true, 48),
('w49', 'Imli Crunchy Coho', 'Tangy imli with crunchy chocolate waffle', 90, NULL, NULL, NULL, 'Waffles', true, 49),
('w50', 'Double Chocolate', 'Double layered chocolate waffle', 110, NULL, NULL, NULL, 'Waffles', true, 50),
('wc1', 'Circle of Bliss (Single)', 'Single layer waffle cake', 300, NULL, NULL, NULL, 'Waffle Cakes', true, 51),
('wc2', 'Circle of Bliss (Double)', 'Double layer waffle cake', 480, NULL, NULL, NULL, 'Waffle Cakes', true, 52),
('wc3', 'Chunks of Heaven (Single)', 'Single layer chunky waffle cake', 330, NULL, NULL, NULL, 'Waffle Cakes', true, 53),
('wc4', 'Chunks of Heaven (Double)', 'Double layer chunky waffle cake', 550, NULL, NULL, NULL, 'Waffle Cakes', true, 54),
('wc5', 'Red Velvet Love Bite (Single)', 'Single layer red velvet cake', 350, NULL, NULL, NULL, 'Waffle Cakes', true, 55),
('wc6', 'Red Velvet Love Bite (Double)', 'Double layer red velvet cake', 600, NULL, NULL, NULL, 'Waffle Cakes', true, 56),
('sp1', 'Salted Spiral', 'Classic salted spiral potato', 80, NULL, NULL, NULL, 'Spiral Potatoes', true, 57),
('sp2', 'Peri Peri Spiral', 'Spicy peri peri flavored spiral', 80, NULL, NULL, NULL, 'Spiral Potatoes', true, 58),
('sp3', 'Chili Limon Spiral', 'Tangy chili lemon spiral', 80, NULL, NULL, NULL, 'Spiral Potatoes', true, 59),
('sp4', 'Chunky Funky Spiral', 'Loaded chunky spiral potato', 80, NULL, NULL, NULL, 'Spiral Potatoes', true, 60),
('hc1', 'Belgian Chocolate', 'Rich Belgian hot chocolate', 100, NULL, NULL, NULL, 'Hot Chocolate', true, 61),
('hc2', 'Caramel Kiss', 'Caramel flavored hot chocolate', 100, NULL, NULL, NULL, 'Hot Chocolate', true, 62),
('hc3', 'Almond Bliss', 'Almond infused hot chocolate', 100, NULL, NULL, NULL, 'Hot Chocolate', true, 63),
('hc4', 'Choko La Coffee', 'Coffee meets hot chocolate', 100, NULL, NULL, NULL, 'Hot Chocolate', true, 64),
('hc5', 'White Rose', 'White chocolate rose flavor', 100, NULL, NULL, NULL, 'Hot Chocolate', true, 65),
('ic1', 'Black Currant', 'Black currant ice cream cone', 50, NULL, NULL, NULL, 'Ice Cream', true, 66),
('ic2', 'Vanilla', 'Classic vanilla ice cream cone', 50, NULL, NULL, NULL, 'Ice Cream', true, 67),
('ic3', 'Strawberry', 'Strawberry ice cream cone', 50, NULL, NULL, NULL, 'Ice Cream', true, 68),
('ic4', 'Butter Scotch', 'Butterscotch ice cream cone', 50, NULL, NULL, NULL, 'Ice Cream', true, 69),
('ic5', 'Tutti Fruity', 'Tutti fruity ice cream cone', 50, NULL, NULL, NULL, 'Ice Cream', true, 70),
('ic6', 'Chocolate Chips', 'Choco chip ice cream cone', 50, NULL, NULL, NULL, 'Ice Cream', true, 71),
('ic7', 'American Nut', 'American nut ice cream cone', 50, NULL, NULL, NULL, 'Ice Cream', true, 72),
('ic8', 'Paan Raseela', 'Paan flavored ice cream cone', 50, NULL, NULL, NULL, 'Ice Cream', true, 73),
('ff1', 'Regular Fry', 'Classic crispy french fries', 80, NULL, NULL, NULL, 'French Fries', true, 74),
('ff2', 'Peri Peri Fry', 'Spicy peri peri seasoned fries', 100, NULL, NULL, NULL, 'French Fries', true, 75),
('ff3', 'Masala Fry', 'Indian masala seasoned fries', 90, NULL, NULL, NULL, 'French Fries', true, 76),
('ff4', 'Cheese Fry', 'Cheesy loaded french fries', 100, NULL, NULL, NULL, 'French Fries', true, 77),
('vs1', 'Veg Sandwich', 'Classic vegetable sandwich', 80, NULL, NULL, NULL, 'Veg Sandwich', true, 78),
('vs2', 'Veg Club Sandwich', 'Triple layered veg club sandwich', 120, NULL, NULL, NULL, 'Veg Sandwich', true, 79),
('vs3', 'Cheese Grilled Sandwich', 'Melted cheese grilled sandwich', 90, NULL, NULL, NULL, 'Veg Sandwich', true, 80),
('vs4', 'Paneer Grilled Sandwich', 'Paneer stuffed grilled sandwich', 130, NULL, NULL, NULL, 'Veg Sandwich', true, 81),
('cs1', 'Chicken Club Sandwich', 'Loaded chicken club sandwich', 180, NULL, NULL, NULL, 'Chicken Sandwich', false, 82),
('cs2', 'Chilli Chicken Sandwich', 'Spicy chilli chicken sandwich', 150, NULL, NULL, NULL, 'Chicken Sandwich', false, 83),
('cs3', 'B.B.Q Chicken Sandwich', 'BBQ glazed chicken sandwich', 150, NULL, NULL, NULL, 'Chicken Sandwich', false, 84),
('cs4', 'Tandoori Chicken Sandwich', 'Tandoori chicken sandwich', 150, NULL, NULL, NULL, 'Chicken Sandwich', false, 85),
('vb1', 'Aloo Tikki Burger', 'Crispy aloo tikki patty burger', 65, NULL, NULL, NULL, 'Veg Burger', true, 86),
('vb2', 'Veg Cheese Burger', 'Veg patty with melted cheese', 90, NULL, NULL, NULL, 'Veg Burger', true, 87),
('vb3', 'Paneer Cheese Burger', 'Paneer patty with cheese', 110, NULL, NULL, NULL, 'Veg Burger', true, 88),
('vb4', 'Veg Burger', 'Classic vegetable burger', 75, NULL, NULL, NULL, 'Veg Burger', true, 89),
('cb1', 'Chicken Burger', 'Classic chicken patty burger', 110, NULL, NULL, NULL, 'Chicken Burger', false, 90),
('cb2', 'Jumbo Chicken Burger', 'Extra large chicken burger', 150, NULL, NULL, NULL, 'Chicken Burger', false, 91),
('mg1', 'Plain Maggi', 'Classic plain Maggi noodles', 50, NULL, NULL, NULL, 'Maggi', true, 92),
('mg2', 'Veg Maggi', 'Maggi with fresh vegetables', 70, NULL, NULL, NULL, 'Maggi', true, 93),
('mg3', 'Cheese Butter Maggi', 'Maggi with cheese and butter', 80, NULL, NULL, NULL, 'Maggi', true, 94),
('gb1', 'Plain Garlic Bread', 'Classic garlic butter bread', 50, NULL, NULL, NULL, 'Garlic Bread', true, 95),
('gb2', 'Cheese Garlic Bread', 'Cheesy garlic bread', 75, NULL, NULL, NULL, 'Garlic Bread', true, 96),
('gb3', 'Peri Peri Garlic Bread', 'Spicy peri peri garlic bread', 80, NULL, NULL, NULL, 'Garlic Bread', true, 97),
('gb4', 'Mexican Garlic Bread', 'Mexican style garlic bread', 80, NULL, NULL, NULL, 'Garlic Bread', true, 98),
('gb5', 'Single Topping Garlic Bread', 'Paneer or corn topping', 80, NULL, NULL, NULL, 'Garlic Bread', true, 99),
('gb6', 'Multi Cheese Garlic Bread', 'Multiple cheese garlic bread', 90, NULL, NULL, NULL, 'Garlic Bread', true, 100),
('vp1', 'Margherita', 'Classic margherita pizza', 90, 160, 'Regular', 'Large', 'Veg Pizza', true, 101),
('vp2', 'Classic Farm House', 'Farm fresh veggie pizza', 100, 180, 'Regular', 'Large', 'Veg Pizza', true, 102),
('vp3', 'Multi Cheese Pizza', 'Loaded with multiple cheeses', 110, 220, 'Regular', 'Large', 'Veg Pizza', true, 103),
('vp4', 'Paneer Pizza', 'Paneer topped pizza', 120, 230, 'Regular', 'Large', 'Veg Pizza', true, 104),
('vp5', 'Mexican Pizza', 'Mexican spiced pizza', 120, 220, 'Regular', 'Large', 'Veg Pizza', true, 105),
('vp6', 'B.B.Q. Pizza', 'BBQ sauce pizza', 120, 210, 'Regular', 'Large', 'Veg Pizza', true, 106),
('vp7', 'Single Topping Pizza', 'Choose your topping', 95, 190, 'Regular', 'Large', 'Veg Pizza', true, 107),
('cp1', 'Chicken Pizza', 'Classic chicken pizza', 140, 250, 'Regular', 'Large', 'Chicken Pizza', false, 108),
('cp2', 'B.B.Q. Chicken Pizza', 'BBQ chicken pizza', 150, 260, 'Regular', 'Large', 'Chicken Pizza', false, 109),
('cp3', 'Chilli Chicken Pizza', 'Spicy chilli chicken pizza', 160, 270, 'Regular', 'Large', 'Chicken Pizza', false, 110),
('cp4', 'Tandoori Chicken Pizza', 'Tandoori chicken pizza', 160, 280, 'Regular', 'Large', 'Chicken Pizza', false, 111),
('pa1', 'White Sauce Pasta', 'Creamy white sauce pasta', 160, NULL, NULL, NULL, 'Pasta', true, 112),
('pa2', 'Red Sauce Pasta', 'Tangy red sauce pasta', 150, NULL, NULL, NULL, 'Pasta', true, 113),
('pa3', 'Pink Sauce Pasta', 'Mixed pink sauce pasta', 180, NULL, NULL, NULL, 'Pasta', true, 114),
('qb1', 'Chicken Wings (3 Pcs)', 'Crispy chicken wings', 150, NULL, NULL, NULL, 'Quick Bites', false, 115),
('qb2', 'Chicken Wings (6 Pcs)', 'Crispy chicken wings', 250, NULL, NULL, NULL, 'Quick Bites', false, 116),
('qb3', 'Chicken Nuggets (4 Pcs)', 'Golden chicken nuggets', 100, NULL, NULL, NULL, 'Quick Bites', false, 117),
('qb4', 'Chicken Nuggets (8 Pcs)', 'Golden chicken nuggets', 150, NULL, NULL, NULL, 'Quick Bites', false, 118),
('qb5', 'Cheese Balls (10 Pcs)', 'Crispy cheese balls', 100, NULL, NULL, NULL, 'Quick Bites', true, 119),
('qb6', 'Momos (8 Pcs)', 'Steamed momos', 90, NULL, NULL, NULL, 'Quick Bites', true, 120),
('qb7', 'Cheese Fingers (8 Pcs)', 'Crispy cheese fingers', 100, NULL, NULL, NULL, 'Quick Bites', true, 121),
('qb8', 'Kurkure Momos (8 Pcs)', 'Crunchy kurkure momos', 100, NULL, NULL, NULL, 'Quick Bites', true, 122),
('qb9', 'Chicken Momos (8 Pcs)', 'Steamed chicken momos', 120, NULL, NULL, NULL, 'Quick Bites', false, 123),
('qb10', 'Chicken Cheese Balls (8 Pcs)', 'Crispy chicken cheese balls', 130, NULL, NULL, NULL, 'Quick Bites', false, 124),
('qb11', 'Veg Cheese Balls (8 Pcs)', 'Crispy veg cheese balls', 100, NULL, NULL, NULL, 'Quick Bites', true, 125),
('qb12', 'Veg Momos (8 Pcs)', 'Steamed veg momos', 80, NULL, NULL, NULL, 'Quick Bites', true, 126),
('qb13', 'Paneer Momos (8 Pcs)', 'Steamed paneer momos', 120, NULL, NULL, NULL, 'Quick Bites', true, 127),
('te1', 'Elaichi Tea', 'Cardamom flavored tea', 30, NULL, NULL, NULL, 'Tea', true, 128),
('te2', 'Masala Tea', 'Spiced masala chai', 30, NULL, NULL, NULL, 'Tea', true, 129),
('te3', 'Ginger Tea', 'Fresh ginger tea', 30, NULL, NULL, NULL, 'Tea', true, 130),
('te4', 'Regular Tea', 'Classic regular tea', 20, NULL, NULL, NULL, 'Tea', true, 131),
('co1', 'Plain Coffee', 'Simple brewed coffee', 40, NULL, NULL, NULL, 'Coffee', true, 132),
('co2', 'Black Coffee', 'Strong black coffee', 30, NULL, NULL, NULL, 'Coffee', true, 133),
('co3', 'Café Latte', 'Smooth café latte', 50, NULL, NULL, NULL, 'Coffee', true, 134),
('co4', 'Café Mocha', 'Chocolate café mocha', 50, NULL, NULL, NULL, 'Coffee', true, 135),
('co5', 'Cappuccino', 'Frothy cappuccino', 60, NULL, NULL, NULL, 'Coffee', true, 136),
('it1', 'Lemon Ice Tea', 'Refreshing lemon iced tea', 100, NULL, NULL, NULL, 'Ice Tea', true, 137),
('it2', 'Peach Ice Tea', 'Sweet peach iced tea', 100, NULL, NULL, NULL, 'Ice Tea', true, 138),
('it3', 'Watermelon Ice Tea', 'Cool watermelon iced tea', 120, NULL, NULL, NULL, 'Ice Tea', true, 139),
('it4', 'Mojito', 'Classic refreshing mojito', 80, NULL, NULL, NULL, 'Ice Tea', true, 140),
('it5', 'Cool Blue', 'Blue curacao cooler', 100, NULL, NULL, NULL, 'Ice Tea', true, 141),
('it6', 'Watermelon Mojito', 'Watermelon mint mojito', 120, NULL, NULL, NULL, 'Ice Tea', true, 142),
('sh1', 'Vanilla Shake', 'Classic vanilla milkshake', 100, NULL, NULL, NULL, 'Shakes', true, 143),
('sh2', 'Cold Coffee', 'Iced cold coffee', 90, NULL, NULL, NULL, 'Shakes', true, 144),
('sh3', 'Chocolate Shake', 'Rich chocolate milkshake', 120, NULL, NULL, NULL, 'Shakes', true, 145),
('sh4', 'Oreo Shake', 'Creamy Oreo milkshake', 120, NULL, NULL, NULL, 'Shakes', true, 146),
('sh5', 'Kit Kat Shake', 'KitKat blended milkshake', 120, NULL, NULL, NULL, 'Shakes', true, 147),
('sh6', 'Banana Shake', 'Fresh banana milkshake', 80, NULL, NULL, NULL, 'Shakes', true, 148),
('sh7', 'Mango Shake', 'Tropical mango milkshake', 90, NULL, NULL, NULL, 'Shakes', true, 149),
('sh8', 'Strawberry Shake', 'Sweet strawberry milkshake', 90, NULL, NULL, NULL, 'Shakes', true, 150),
('sh9', 'Cold Coffee With Ice Cream', 'Cold coffee topped with ice cream', 120, NULL, NULL, NULL, 'Shakes', true, 151);
